## Упражнения по библиотеке Numpy

In [1]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [22]:
arr = np.random.randint(0, 11, size=20) 
print("Oriignal array:")
print(arr)

mask = (arr > 3) & (arr < 8)    #  3 < x < 8  mask == boolean фккфн
arr[mask] = -arr[mask]
print("\n Updated array:")
print(arr)

Oriignal array:
[ 5 10  1  6  0 10 10  7  1  8  4  0  6  4  8  0  8  0  2  0]

 Updated array:
[-5 10  1 -6  0 10 10 -7  1  8 -4  0 -6 -4  8  0  8  0  2  0]


**2.** Заменить максимальный элемент случайного массива на 0

In [30]:
arr = np.random.randint(1, 21, size=15)
print("Original array:", arr)


print("Max :", arr.max())
arr[arr == arr.max()] = 0

print("Result:", arr)

Original array: [ 8  2 11  9 13  8 19  6  3 12  5  5  2  1  9]
Max : 19
Result: [ 8  2 11  9 13  8  0  6  3 12  5  5  2  1  9]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [35]:
import numpy as np

vectors = [
    [1, 2, 3],
    [10, 20]
]

result = []
for x in vectors[0]:
    for y in vectors[1]:
        result.append([x, y])

print("All combinations:")
for i in result:
    print(i, "\n")
print(f"Total number of combinations: {len(result)}")   

All combinations:
[1, 10] 

[1, 20] 

[2, 10] 

[2, 20] 

[3, 10] 

[3, 20] 

Total number of combinations: 6


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [97]:
A = np.array([
    [1, 2, 3],
    [3, 4, 2],
    [5, 1, 2],
    [7, 8, 2],
    [2, 1, 4],
    [5, 1, 7],
    [1, 2, 5],
    [2, 3, 1]
])

B = np.array([
    [1, 2],
    [3, 4]
])

mask = (
    np.any(np.isin(A, B[0]), axis=1) &   # at lease one from  B[0]
    np.any(np.isin(A, B[1]), axis=1)     # at least one from B[1]
)

indexes = np.where(mask)[0]
print(indexes)

[0 1 4 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [93]:
A = np.array([
    [2, 2, 2],   # del
    [1, 3, 4],   
    [5, 5, 5],   # del
    [3, 1, 3],   
    [4, 4, 1],    
    [2, 2, 1],    
    [6, 6, 6],   # del
    [1, 2, 1],    
    [3, 3, 3],   # del
    [4, 1, 4]    
])

print("Original matrix")
print(A)
print()

# compare min and max 
mask = A.max(axis=1) != A.min(axis=1)  

result = A[mask]

print("Final matrix:")
print(result)


Original matrix
[[2 2 2]
 [1 3 4]
 [5 5 5]
 [3 1 3]
 [4 4 1]
 [2 2 1]
 [6 6 6]
 [1 2 1]
 [3 3 3]
 [4 1 4]]

Final matrix:
[[1 3 4]
 [3 1 3]
 [4 4 1]
 [2 2 1]
 [1 2 1]
 [4 1 4]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [101]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],    #
    [1, 2, 3],    # 
    [7, 8, 9],
    [4, 5, 6],    # 
    [1, 2, 3],    # 
    [1, 1, 2]
])

print("Original array:")
print(A)


unique_rows = np.unique(A, axis=0)

print('\n')
print("No duplicates:")
print(unique_rows)

Original array:
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [7 8 9]
 [4 5 6]
 [1 2 3]
 [1 1 2]]


No duplicates:
[[1 1 2]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [105]:
X = [[1, 0, 1],
    [2, 0, 2], 
    [3, 0, 3], 
    [4, 4, 4]]


def prod_nonzero_diag(matrix):
    prod = 1
    for i in range(min(len(matrix), len(matrix[0]))):
        if matrix[i][i] != 0:
            prod *= matrix[i][i]
    return prod

print("No numpy res:", prod_nonzero_diag(X)) 


# with numpy

def prod_nonzero_diag_np(matrix):
    diag = np.diagonal(matrix)              
    return np.prod(diag[diag != 0])          


print("Numpy res:", prod_nonzero_diag_np(X))  

No numpy res: 3
Numpy res: 3


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [110]:
def are_multisets_equal(x, y):
    return sorted(x) == sorted(y)


def are_multisets_equal_np(x, y):
    x, y = np.asarray(x), np.asarray(y)
    return np.array_equal(np.sort(x), np.sort(y))

x = [1, 2, 2, 4]
y = [4, 2, 1, 2]

print(are_multisets_equal(x, y))         
print(are_multisets_equal_np(x, y))       

x2 = [1, 2, 3, 3]
y2 = [3, 1, 2, 4]
print(are_multisets_equal_np(x2, y2))    # False

True
True
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [112]:
x = [6, 2, 0, 3, 0, 0, 5, 7, 0]
#    0  1  2  3  4  5  6  7  8

def max_after_zero(x):
    m = 0
    for i in range(1, len(x)):
        if x[i-1] == 0 and x[i] > m:
            m = x[i]
    return m


print(max_after_zero(x))

def max_after_zero_np(x):
    x = np.array(x)
    return np.max(x[1:][x[:-1] == 0])

print(max_after_zero_np(x))

5
5


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [123]:
def rle_pure(x):
    values, counts = [], []
    for el in x:
        if not values or el != values[-1]:
            values.append(el)
            counts.append(1)
        else:
            counts[-1] += 1
    return values, counts

x = [2, 2, 2, 3, 3, 3, 5]
print(rle_pure(x))   

def rle_np(x):
    x = np.asarray(x)
    if len(x) == 0:
        return [], []
    
    # Индексы начал серий: 0 + все места, где значение меняется
    starts_idx = np.concatenate(([0], np.where(x[1:] != x[:-1])[0] + 1))
    
    values = x[starts_idx]
    counts = np.diff(np.append(starts_idx, len(x)))
    
    return values.tolist(), counts.tolist()


x_np = np.array(x)
print(rle_np(x_np))


([2, 3, 5], [3, 3, 1])
([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [131]:

from math import sqrt
import numpy as np
from scipy.spatial.distance import cdist
import time


def euclidean_distances_py(X, Y):
    """
    distance = sqrt ( sum(x_ik - y_ik)^2 )
    """
    n = len(X)
    m = len(Y)
    D = [[0.0] * m for _ in range(n)]
    for i in range(n):
        for j in range(m):
            dist = 0.0
            for k in range(len(X[i])):
                diff = X[i][k] - Y[j][k]
                dist += diff * diff
            D[i][j] = sqrt(dist)    
    return D


def euclidean_distances_np(X, Y):
    X = np.asarray(X)
    Y = np.asarray(Y)
    XX = np.sum(X * X, axis=1)[:, np.newaxis] # вектор → столбец
    YY = np.sum(Y * Y, axis=1)[np.newaxis, :] # вектор → строка
    XY = X @ Y.T  #матричное умножение
    return np.sqrt(XX + YY - 2 * XY)


"""
Входные данные
n - количество точек в Х
m - количество точек в Y
d - каждая точка - вектор из d чисел
"""
np.random.seed(42)
n, m, d = 10000, 500, 2     
X_np = np.random.randn(n, d)
Y_np = np.random.randn(m, d)
X_list = X_np.tolist()
Y_list = Y_np.tolist()


 
print("Проверка корректности...")
D_py = euclidean_distances_py(X_list, Y_list)
D_np = euclidean_distances_np(X_np, Y_np)
D_scipy = cdist(X_np, Y_np, 'euclidean')

print("Результаты совпадают?", np.allclose(D_py, D_np) and np.allclose(D_np, D_scipy))




print("\nСравнение скорости:")
print("-" * 50)
for name, func, args in [
    ("Python",      euclidean_distances_py,   (X_list, Y_list)),
    ("NumPy", euclidean_distances_np,    (X_np,   Y_np)),
    ("scipy.cdist",        lambda x,y: cdist(x,y,'euclidean'), (X_np, Y_np))
]:
    start = time.time()
    _ = func(*args)
    elapsed = time.time() - start
    print(f"{name:25} {elapsed:.8f} сек")

Проверка корректности...
Результаты совпадают? True

Сравнение скорости:
--------------------------------------------------
Python                    1.12401152 сек
NumPy                     0.07558942 сек
scipy.cdist               0.01074576 сек


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [132]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [133]:
calorie_stats = np.loadtxt(r"C:\MyPythonProjects\numpy_pandas\cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [ ]:
# Среднее количество калорий у конкурентов
average_calories_competitors = np.mean(calorie_stats)

# Наши CrunchieMunchies
crunchie_munchies_calories = 60

# Разница: насколько в среднем конкуренты "тяжелее"
average_calories = average_calories_competitors - crunchie_munchies_calories

print(f"Среднее количество калорий у конкурентов: {average_calories_competitors:.2f}")
print(f"CrunchieMunchies: {crunchie_munchies_calories} калорий")
print(f"В среднем конкуренты содержат на {average_calories:.2f} калорий больше!")

Среднее количество калорий у конкурентов: 106.88
CrunchieMunchies: 60 калорий
В среднем конкуренты содержат на 46.88 калорий больше!


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [11]:
# Сортируем по возрастанию
calorie_stats_sorted = np.sort(calorie_stats)

# Выводим отсортированный массив
print("Калории в хлопьях (от меньшего к большему):")
print(calorie_stats_sorted)

Калории в хлопьях (от меньшего к большему):
[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [14]:
median_calories = np.median(calorie_stats)

print(f"Медиана количества калорий:         {median_calories:.2f}")
print(f"CrunchieMunchies:                    60 калорий")

Медиана количества калорий:         110.00
CrunchieMunchies:                    60 калорий


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [15]:
nth_percentile = None

# Итерируемся по процентилям от 0 до 100
for n in range(101):
    # Рассчитываем n-й процентиль
    percentile_value = np.percentile(calorie_stats, n)

    # Печатаем значение процентиля для отслеживания (как запрошено в задании)
    print(f"{n}-й процентиль: {percentile_value:.2f} калорий")

    # Проверяем, превышает ли значение 60
    if percentile_value > 60:
        # Это наименьший процентиль, удовлетворяющий условию
        nth_percentile = n
        # Выходим из цикла
        break

# Печатаем финальный результат
if nth_percentile is not None:
    final_value = np.percentile(calorie_stats, nth_percentile)
    print("---")
    print(f"Наименьший процентиль (N), превышающий 60 калорий: {nth_percentile}")
    print(f"Значение {nth_percentile}-го процентиля: {final_value:.2f} калорий")
else:
    print("---")
    print("Не удалось найти процентиль, превышающий 60 калорий в этом наборе данных.")

0-й процентиль: 50.00 калорий
1-й процентиль: 50.00 калорий
2-й процентиль: 50.00 калорий
3-й процентиль: 55.60 калорий
4-й процентиль: 70.00 калорий
---
Наименьший процентиль (N), превышающий 60 калорий: 4
Значение 4-го процентиля: 70.00 калорий


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [16]:
# Шаг 1: Создаем логический массив, где True = калорий > 60
mask = calorie_stats > 60

# Шаг 2: Подсчитываем количество хлопьев с более чем 60 калориями
# np.sum() суммирует True (1) и False (0)
count_more_than_60 = np.sum(mask)

# Шаг 3: Общее количество конкурентов
total_competitors = len(calorie_stats)

# Шаг 4: Рассчитываем процент и сохраняем его в more_calories
more_calories = (count_more_than_60 / total_competitors) * 100

# Распечатываем результат
print(f"Количество конкурентов с более чем 60 калориями: {count_more_than_60}")
print(f"Общее количество конкурентов: {total_competitors}")
print(f"Процент конкурентов с более чем 60 калориями (more_calories): {more_calories:.2f}%")

Количество конкурентов с более чем 60 калориями: 74
Общее количество конкурентов: 77
Процент конкурентов с более чем 60 калориями (more_calories): 96.10%


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [17]:
# Рассчитываем стандартное отклонение
calorie_std = np.std(calorie_stats)

# Выводим результат
print(f"Стандартное отклонение количества калорий (calorie_std): {calorie_std:.2f}")

Стандартное отклонение количества калорий (calorie_std): 19.36


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [ ]:
"""
Полученные результаты исследования говорят о том, что наши злаки менее калорийные (на 40% ), чем у конкурентов в 95 5 случаев, поэтому маркетологам
можно посоветовать делать упор на этот факт при продвижении товара на рынке и активно его предлагать потребителям, которые следят за 
количеством каллорий

"""